# Generated by Django 4.0.5 on 2022-06-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_task',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateField(null=True, verbose_name='Дата выполнения'),
        ),
    ]
