# Generated by Django 4.0.5 on 2022-06-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_task_created_task_alter_task_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
