# Generated by Django 4.0.5 on 2022-06-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_task_dead_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='No Title', max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_task',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
