# Generated by Django 4.0.5 on 2022-06-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_task_title_alter_task_created_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sketchpad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=20, verbose_name='Статус')),
                ('created_note', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_of_completion', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('title', models.CharField(default='No Title', max_length=50, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'Список задач',
                'db_table': 'task',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
