# Generated by Django 4.0.5 on 2022-06-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_sketchpad_delete_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sketchpad',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Список задач'},
        ),
        migrations.AlterModelTable(
            name='sketchpad',
            table='sketchpad',
        ),
    ]
